# Generated by Django 3.2.4 on 2021-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='stars',
            field=models.SmallIntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'four_stars'), (5, 'five stars')], default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='stars',
            field=models.SmallIntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'four_stars'), (5, 'five stars')], default=1),
        ),
    ]
