# Generated by Django 3.2.4 on 2021-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210619_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
