# Generated by Django 3.2.4 on 2021-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_getintouch_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
