# Generated by Django 3.2.4 on 2021-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20210621_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='descriptionA',
        ),
        migrations.AddField(
            model_name='blog',
            name='descriptionB',
            field=models.CharField(default='exit', max_length=1000),
            preserve_default=False,
        ),
    ]
